name: Processing invalid data

on:

  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Testing for invalid
        run: python -m unittest test_func_processing_invalid_data.py

      - uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: 933027728
          token: 5051639728:AAFf69jhBUdCKFArmpclxyRiocyrXpwZozQ
          status: ${{ job.status }}
